name = "mode"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true
routes = [
  { pattern = "vipren.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.vipren.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.vipren.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.vipren.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vipren.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.vipren.biz.id", custom_domain = true },  
  { pattern = "cache.netflix.com.vipren.biz.id", custom_domain = true },
]


[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/ReNchi-Z/inconigto-vpn/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/ReNchi-Z/inconigto-vpn/refs/heads/main/web/sub.html"
COSTUM_PAGE_URL = "https://raw.githubusercontent.com/ReNchi-Z/inconigto-vpn/refs/heads/main/web/costum.html"

